### PR TITLE
Python code formatting

### PR DESCRIPTION
**Pull request by luizirber**
Some reformatting of `plotcount.py` and `wordcount.py`:

  - Remove unused `import string`
  - Make docstrings from function comments
  - Reindent to 4 spaces
  - Try to make DELIMITERS clearer to read
  - `iter(list())` is not necessary for dict `items()`

### CODE REVIEW

**Comment by luizirber** [comment]
Also regenerated `make-lesson.tar.gz`.

**Comment by wking** [comment]
On Sat, Nov 14, 2015 at 02:56:40PM -0800, Luiz Irber wrote:
> Some reformatting of `plotcount.py` and `wordcount.py`:

+1 :).  This bothered me recently, but not enough to work up a PR.
I'd suggest washing the results through pylint and pep8 to see if
anything else shakes out, but this is a step in the right direction
either way.

**Comment by luizirber** [comment]
It's clean on pep8, I'll run pylint and see what shows up.

**Comment by luizirber** [comment]
OK, I fixed the more obvious ones (parenthesis around `if` conditions, avoid using builtins as variable names, use context managers for file opening/closing), there are still warnings left but I don't really agree with the proposed changes.

```
$ pylint plotcount.py wordcount.py
************* Module plotcount
C:  1, 0: Missing module docstring (missing-docstring)
W: 10,21: Redefining name 'counts' from outer scope (line 32) (redefined-outer-name)
W: 10,29: Redefining name 'limit' from outer scope (line 29) (redefined-outer-name)
C: 21, 4: Invalid variable name "ax" (invalid-name)
C: 27, 4: Invalid constant name "input_file" (invalid-name)
C: 28, 4: Invalid constant name "output_file" (invalid-name)
C: 29, 4: Invalid constant name "limit" (invalid-name)
C: 31, 8: Invalid constant name "limit" (invalid-name)
C: 32, 4: Invalid constant name "counts" (invalid-name)
************* Module wordcount
C:  1, 0: Missing module docstring (missing-docstring)
W: 85,31: Redefining name 'min_length' from outer scope (line 128) (redefined-outer-name)
W:111,27: Redefining name 'output_file' from outer scope (line 127) (redefined-outer-name)
W:111,40: Redefining name 'min_length' from outer scope (line 128) (redefined-outer-name)
W:111,15: Redefining name 'input_file' from outer scope (line 126) (redefined-outer-name)
C:126, 4: Invalid constant name "input_file" (invalid-name)
C:127, 4: Invalid constant name "output_file" (invalid-name)
C:128, 4: Invalid constant name "min_length" (invalid-name)
C:130, 8: Invalid constant name "min_length" (invalid-name)
```

**Comment by luizirber** [comment]
And this one is probably another PR, but I think the code gets clearer if we use the `collections.Counter`: https://gist.github.com/c9d6e7a1e681bab8f4a1
(still need to update docstrings).

**Comment by wking** [comment]
On Sat, Nov 14, 2015 at 04:22:31PM -0800, Luiz Irber wrote:
> C:  1, 0: Missing module docstring (missing-docstring)

This one is usually a good idea, since it provides a convenient place
to say what the script is for.

> W: 10,21: Redefining name 'counts' from outer scope (line 32) (redefined-outer-name)
> W: 10,29: Redefining name 'limit' from outer scope (line 29) (redefined-outer-name)

I agree that these are ignorable.

> C: 21, 4: Invalid variable name "ax" (invalid-name)

I'd prefer axes here.  No need to abbreviate names.

> C: 27, 4: Invalid constant name "input_file" (invalid-name)
> C: 28, 4: Invalid constant name "output_file" (invalid-name)
> C: 29, 4: Invalid constant name "limit" (invalid-name)
> C: 31, 8: Invalid constant name "limit" (invalid-name)
> C: 32, 4: Invalid constant name "counts" (invalid-name)

These are probably because pylint thinks we're defining global
constants (where it prefers caps, see const-rgx under [1]).  I'm fine
ignoring these, but it might be useful to shift the __main__ stuff
into a function:

  def run(input_path, output_path, limit=10):
      counts = load_word_counts(input_path)
      …

  if __name__ == '__main__':
      run(input_path=sys.argv[1],
          output_path=sys.argv[2],
          limit=sys.argv[3] if len(sys.argv) > 3 else 10)

That makes it possible to use the __main__ logic from another program
if it turns out to be convenient.

[1]: http://docs.pylint.org/features.html#id10

**Comment by mikej888** [comment]
Thanks! As it was a "black box" program I didn't bother cleaning it up, but, of course, workshop attendees may look at it.

**Pull request merged**
