### PR TITLE
Add template language for issues and PRs about lesson contribution an…

### PR DESCRIPTION
**Pull request by ErinBecker**
…d maintenance process

### CODE REVIEW

**Comment by ErinBecker** [comment]
I realized after submitting this PR yesterday that I didn't do a good job of documenting the rationale behind this or what it's trying to accomplish. My apologies.

I've been getting a significant number of questions from new instructors and instructor trainees about the lesson contribution process. Specifically, many trainees are worried that if their contributions aren't accepted they won't be able to qualify as instructors. Some are also worried or frustrated about not hearing back about their contributions for a while. I wanted to help communicate to contributors that the maintainers are volunteers who have many other time commitments and sometimes delay in reviewing PRs is inevitable, also that even if a specific contribution isn't incorporated, their input is still appreciated and welcome.

I'm hopeful that this language will help clarify the process and assuage some of these concerns, especially for new members of our community.

**Comment by lexnederbragt** [comment]
Would it be help if after logging the contribution into AMY (as part of checkout), an email is sent out to the trainee with 'thank you for your contribution, this means you have fulfilled this part of the checkout procedure. What may happen next to your contribution is this: accept, reject, long wait etc"

**Comment by ErinBecker** [comment]
Based on comments on other repos, I've added the PR to the styles repo: https://github.com/swcarpentry/styles/pull/143

**Comment by ErinBecker** [comment]
@lexnederbragt I agree that having an automated message go out to trainees would be ideal. I think it's also important, thought, for contributors who aren't trainees to know that it might be a while before their PR/issue is resolved. So to my mind this is a more general communication that should be viewed by all contributors. What do you think?

Closing because of duplicate PR now in styles.

**Pull request closed without merging**
