### PR TITLE
Updating mailmap and AUTHORS before release

### PR DESCRIPTION
**Pull request by twitwi**

### CODE REVIEW

**Comment by gcapes** [comment]
Hi @twitwi ,
Could you give me some background to this PR please? I can't see where these files are used on the .io site, and what is the rationale for the changes made?
Thanks

**Comment by twitwi** [comment]
Sure. Sorry for the lack of details: I opened PRs on each lesson and have been lazy.
Thanks for the question :), I'll be propagating these details to other PRs.

The authors file is used to list all authors of the lesson, which currently means "people having commited to the repo". This file is used for the release of the lessons (where we get a DOI from Zenodo, publish on our site [1], etc).

We generate the authors file from `git log` by using the commiter names. However, for a same person we have commits showing different emails, different writings of the name, a pseudo instead of the name, etc. Git has the `.mailmap` mechanism [2] exactly to solve this issue by describing how commits should be patched. This file used to be filled manually (leading to useless entries, missing ones, errors) and it is now assisted by a script, leading to some notable cleanup.

[1] https://software-carpentry.org/lessons/previous/
[2] https://git-scm.com/docs/git-shortlog#_mapping_authors

**Comment by gcapes** [comment]
Thanks for the background - it makes a lot more sense now. 

However, I notice that while my name remains in the AUTHORS file, it is removed .mailmap file. Does that just mean there is a duplicate entry (i.e. I've used two different email addresses)?
Thanks

**Comment by twitwi** [comment]
Your name appearing in the AUTHORS file means you (still) appear in git log.
Your name disappearing from the .mailmap means that all your commits are already showing your correct name (which is good) and thus that the entry in the .mailmap was unnecessary.
Cheers.

**Comment by gcapes** [comment]
Great, thanks!

**Pull request merged**
