### PR TITLE
A little update about GNU Make comment.

### PR DESCRIPTION
**Pull request by LiuGangKingston**
For qualifying as an instructor of the Software Carpentry.

### CODE REVIEW

**Comment by wking** [comment]
This looks like a reroll of #26 (and you can update existing pull
requests by updating your branch [1], there's no need to open a new
request).

[1]: https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

**Comment by LiuGangKingston** [comment]
Hi, Trevor,


Thanks for telling me!


What I usually do is to re-do everything for correcting, if possible.


Best Wishes!

Gang Liu

http://www.hpcvl.org
Queen's University
Kingston, ON
613-533-6000 ext.78387
gang.liu@queensu.ca

Dynamical Equations of Period Vectors:
Can. J. Phys. Vol.93 No.9: 974-978 (2015)
http://dx.doi.org/10.1139/cjp-2014-0518
http://arxiv.org/abs/cond-mat/0209372v16
https://github.com/LiuGangKingston






________________________________

**Comment by wking** [comment]
On Mon, Nov 16, 2015 at 09:47:13AM -0800, Gang Liu wrote:
> What I usually do is to re-do everything for correcting, if possible.

Redoing your commit is fine, but then:

  $ git push --force $your_remote $your_branch

for example:

  $ git push --force LiuGangKingston gh-pages

to update the original pull request.  Easier for you (no need to write
up another pull-request message, just comment in the original
summarizing your changes), and easier for the maintainer (all the
discussion is collected in one place, instead of being split over
multiple pull requests).

**Comment by LiuGangKingston** [comment]
HI Trevor ,


Thank you again and also sorry for the inconvenience!


What I did is to delete all my old items including the pull request, then fork, clone, update, push, and make another pull request.


Best Wishes!

Gang Liu

http://www.hpcvl.org
Queen's University
Kingston, ON
613-533-6000 ext.78387
gang.liu@queensu.ca

Dynamical Equations of Period Vectors:
Can. J. Phys. Vol.93 No.9: 974-978 (2015)
http://dx.doi.org/10.1139/cjp-2014-0518
http://arxiv.org/abs/cond-mat/0209372v16
https://github.com/LiuGangKingston






________________________________

**Pull request merged**
