### PR TITLE
Update style to v9.1.1

### PR DESCRIPTION
**Pull request by rgaiacs**
A few changes on style.

### CODE REVIEW

**Comment by gcapes** [comment]
Hi @rgaiacs, 

There are lots of conflicts and mention of hpc-shell in this PR. Are you sure you have the right branch?

**Comment by rgaiacs** [comment]
> There are lots of conflicts and mention of hpc-shell in this PR. Are you sure you have the right branch?

Issue with my bash script. It should be fixed now.

**Comment by gcapes** [comment]
Thanks @rgaiacs,
It looks good apart from the one commit I commented on above.

**Comment by rgaiacs** [comment]
> Download files used in the lesson
> or
> Download files required for the lesson

I don't have a strong preference.

**Comment by gcapes** [comment]
Ok, let's go with "Download files required for the lesson".
Could you edit the commit and rebase? Or just add another commit to this branch? That way all the lessons should get the correction.
Thanks!

**Comment by rgaiacs** [comment]
@gcapes I couldn't find "Download files required for the lesson."

~~~
$ grep -ir download code data _episodes _episodes_rmd _extras _includes _layouts *.md
data/books/LICENSE_TEXTS.md:before downloading, copying, displaying, performing, distributing or
_episodes/07-functions.md:> Project Gutenberg offers thousands of free ebooks to download.
_episodes/07-functions.md:> * download the 'Plain Text UTF-8' version and save it to the `books` folder; 
_extras/guide.md:Or, ask students to download
_extras/guide.md:To download and build makefile2graph on Linux:
_extras/discuss.md:  Make to download and convert data.
index.md:> In order to follow this lesson, you will need to download some files.
setup.md:You need to download some files to follow this lesson:
setup.md:1. Download [make-lesson.zip][zip-file].
setup.md:4. Navigate to the directory where you downloaded the file.
setup.md:You will need to have Xcode installed (download from the
setup.md:Anaconda python <https://www.continuum.io/downloads> which includes all of the
~~~

> Could you edit the commit and rebase?

No. Rebase is "evil" after you push your changes to a shared remote repository.

> Or just add another commit to this branch?

The pull request was generated by a script, see https://github.com/swcarpentry/infra-lessons. Any change on this pull request need to go first at https://github.com/swcarpentry/styles.

**Comment by gcapes** [comment]
Hi @rgaiacs, 
I'm asking for a change to the wording before merging this pull request. The current wording is poor English.

I thought I'd commented directly on the commit, and have just done so again, so that it's clear what I'm asking for. However, I can't seem to find that request for change on GitHub - perhaps it's the same for you. It's commit 4b90bb3858df92704 which needs changing. Line 21 should be replaced with this:

    <td class="col-md-7">Dowload files required for the lesson.</td>

Please make the change to the syllabus.html file and add a commit to this branch.
Thanks

**Comment by rgaiacs** [comment]
> Please make the change to the syllabus.html file and add a commit to this branch.

Done.

**Pull request merged**
